### ISSUE TITLE
Item Changes

### ISSUE THREAD

**Issue by kosalaindrasiri** [kosalaindrasiri/rentIt#2]
Item Should have following attributes: 
- Name
- Code
- Image Url 
- Purchased Price
- Availability 
- Rent price per day 

Update Database, views and Item controller accordingly. 
Image should not be required.

**Comment by kosalaindrasiri** [comment]
- There should not be a "price" field. 
- Attributes should be in the given order 
- ***_Image should not be required.**_

**Comment by damith322** [comment]
rebase conflict was solved now  you can merge it
